# Phi 4 configuration

model:
  # Model identifier
  name: "microsoft/phi-2"  # Using Phi-2 for now as Phi-4 isn't released yet
  display_name: "Phi 4"  # For display in CLI
  type: "causal"
  
  # Model-specific paths
  pretrained_path: ${paths.pretrained}/phi4
  # finetuned_path: ${paths.finetuned}/gflownet/phi4
  
  # Model-specific configurations
  trust_remote_code: true
  use_auth_token: ${oc.env:HF_TOKEN}
  revision: "main"
  torch_dtype: "bfloat16"
  
  model_kwargs:
    device_map: "auto"
    load_in_4bit: true
    max_memory:
      0: "24GiB"  # Adjust based on your GPU memory
  
  # Generation configurations
  generation:
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 0.9
    repetition_penalty: 1.1
    do_sample: true
