# Main configuration file for GF-ODG project

# Path configurations
paths:
  root: ${oc.env:PROJECT_ROOT,/net/scratch2/listar2000/gfn-od}
  models: ${paths.root}/models
  pretrained: ${paths.models}/pretrained
  finetuned: ${paths.models}/finetuned
  utils: ${paths.models}/utils

# Available model configurations
defaults:
  - _self_
  - models: gemma-2b  # default model

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: ${paths.root}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${paths.root}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
