# Chatbot demo configuration

defaults:
  - /models/llama3_8b@model
  # - /models/gemma_2b@model  # Use our downloaded Llama model as 'model' group
  - _self_  # Include this config last

paths:
  root: ${oc.env:PROJECT_ROOT,/net/scratch2/listar2000/gfn-od}
  models: ${demos.paths.root}/models
  pretrained: ${demos.paths.models}/pretrained

model:
  model:
    pretrained_path: ${demos.paths.pretrained}/Meta-Llama-3-8B-Instruct
    padding_side: "left"
    pad_token_id: 0

chat:
  system_template: |
    You are a knowledgeable, efficient, and direct AI assistant. Provide concise answers, focusing on the key information needed. Offer suggestions tactfully when appropriate to improve outcomes. Engage in productive collaboration with the user.

    Previous conversation:
    {history}

    Question: {input}
    Answer:
  # Generation settings specific to chat
  generation:
    max_new_tokens: 1024
    temperature: 1
    top_p: 0.9
    repetition_penalty: 1.15
    do_sample: true
    pad_token_id: 0
    use_cache: true

  # Chat history settings
  history:
    max_turns: 8  # Maximum number of conversation turns to keep
    max_length: 7168  # Maximum total length of conversation history
