# Chatbot demo configuration

defaults:
  - /models/deepseek-8b@model
  # - /models/gemma_2b@model  # Use our downloaded Llama model as 'model' group
  - _self_  # Include this config last

paths:
  root: ${oc.env:PROJECT_ROOT,/net/scratch2/caom/gf-odg}
  models: ${demos.paths.root}/models
  pretrained: ${demos.paths.models}/pretrained

model:
  model:
    pretrained_path: ${demos.paths.pretrained}/DeepSeek-R1-Distill-Llama-8B
    padding_side: "left"
    pad_token_id: 0

chat:
  # Chat template with clear instructions
  system_template: |
    You are a helpful AI assistant. Follow these rules strictly:
    1. Provide direct responses without roleplaying or adding questions
    2. Never include "Human:" or "Assistant:" in your responses
    3. Never ask the human to respond or continue the conversation
    4. Focus on giving complete, self-contained answers
    5. Do not add meta-commentary about the conversation
    6. Be concise and finish once you have the answer, do not further include "Question:" or "Answer:" in your response

    Previous conversation:
    {history}

    Human: {input}
    Assistant:

  # Generation settings specific to chat
  generation:
    max_new_tokens: 1024
    temperature: 1
    top_p: 0.9
    repetition_penalty: 1.15
    do_sample: true
    pad_token_id: 0
    use_cache: true

  # Chat history settings
  history:
    max_turns: 8  # Maximum number of conversation turns to keep
    max_length: 7168  # Maximum total length of conversation history